#!/bin/env ruby
#
# $File$
# $DateTime$
#
# $Revision$
# $Author$
#
# 2009 Yahoo
#
#  Test case for getRightsDoc(grd) command

if($0 == __FILE__)
  mydata = File.expand_path(__FILE__).reverse.sub(/.*?atad/,"").reverse;$:.unshift(mydata); $:.unshift(File.join(mydata, 'src', 'ruby')) #append library path
end

require "model"
require "action/verify"
require "action/zmprov"

include Action

#
# Global variable declaration
#
current = Model::TestCase.instance()
current.description = "Test case for getRightsDoc(grd) command"

#
# Setup
#
current.setup = [
 

]
#
# Execution
#
current.action = [

  # Basic grd
  v(ZMProv.new('grd')) do |mcaller, data|
   mcaller.pass = data[0] == 0 && data[1].include?('Generated by: zmprov grd') 
  end,
  v(ZMProv.new('getRightsDoc')) do |mcaller, data|
   mcaller.pass = data[0] == 0 && data[1].include?('Generated by: zmprov grd') 
  end,

  # Invalid option
  v(ZMProv.new('grd','-l')) do |mcaller, data|
   mcaller.pass = data[0] == 0 && data[1].include?('Generated by: zmprov grd -l') 
  end,

]
#
# Tear Down
#
current.teardown = [

]


if($0 == __FILE__)
  require 'engine/simple'
  testCase = Model::TestCase.instance
  Engine::Simple.new(Model::TestCase.instance).run
end